services:
  postgres:
    image: postgres:14-alpine
    volumes:
      - ./postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=verysecretpassword
      - POSTGRES_USER=instabug
      - POSTGRES_DB=instabug
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U instabug"]
      interval: 5s
      timeout: 10s
      retries: 3

  rabbit-mq:
    image: rabbitmq:3.13.2
    healthcheck:
      test: rabbitmq-diagnostics -q ping
      interval: 5s
      timeout: 10s
      retries: 3

  redis:
    image: redis:7.0.15-alpine3.20
    healthcheck:
      test: [ "CMD", "redis-cli", "--raw", "incr", "ping" ]
      interval: 5s
      timeout: 10s
      retries: 3

  app:
    build: .
    command: ./run.sh
    ports:
      - "7000:4000"
    environment:
      - DATABASE_URL=postgresql://instabug:verysecretpassword@postgres:5432/instabug
      - ALLOWED_HOSTS=127.0.0.1
      - DEBUG=True
      - CELERY_BROKER_URL=amqp://guest:guest@rabbit-mq:5672//
      - REDIS_HOST=redis
    depends_on:
      postgres:
        condition: service_healthy
      rabbit-mq:
        condition: service_healthy
      redis:
        condition: service_healthy

  celery:
    build: .
    command: celery -A instabug worker -l INFO
    environment:
      - DATABASE_URL=postgresql://instabug:verysecretpassword@postgres:5432/instabug
      - CELERY_BROKER_URL=amqp://guest:guest@rabbit-mq:5672//
    depends_on:
      rabbit-mq:
        condition: service_healthy
      redis:
        condition: service_healthy
