# Generated by Django 4.2 on 2024-05-18 15:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="State",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("device", models.CharField(max_length=250)),
                ("os", models.CharField(max_length=250)),
                ("memory", models.PositiveBigIntegerField()),
                ("storage", models.PositiveBigIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="Bug",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("application_token", models.CharField(max_length=250)),
                ("number", models.PositiveBigIntegerField()),
                (
                    "status",
                    models.CharField(
                        choices=[("n", "New"), ("i", "In-progress"), ("c", "Closed")],
                        max_length=1,
                    ),
                ),
                (
                    "priority",
                    models.CharField(
                        choices=[(1, "Minor"), (2, "Major"), (3, "Critical")],
                        max_length=1,
                    ),
                ),
                ("comment", models.TextField()),
                (
                    "state",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT, to="bugs.state"
                    ),
                ),
            ],
        ),
        migrations.AddIndex(
            model_name="bug",
            index=models.Index(
                fields=["application_token", "number"],
                name="bugs_bug_applica_1050b1_idx",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="bug",
            unique_together={("application_token", "number")},
        ),
    ]
